#!/system/bin/sh
#GPU Threshold
#Change MALI 400MP GPU Frequency Threshold:
#Battsave

# Threshold0-1/up-down: 50% 42%
# Threshold1-2/up-down: 60% 65%
# Threshold2-3/up-down: 60% 65%
# Threshold3-4/up-down: 60% 65%

echo "30% 22% 50% 45% 50% 45% 50% 45%" > /sys/class/misc/gpu_clock_control/gpu_control

